defmodule SfaceDemoWeb.Components.Card do
  @moduledoc """
  A sample component generated by `mix surface.init`.
  """
  use Surface.Component

  @doc "The header slot"
  slot header

  @doc "The footer slot"
  slot footer

  @doc "The main content slot"
  slot default

  @doc "The background color"
  prop rounded, :boolean, default: false

  @doc "needs an ID for js hook"
  prop id, :string, required: true

  @doc """
  The max width.

  sm: `max-w-sm`, md: `max-w-md`, lg: `max-w-lg`
  """
  prop max_width, :string, values: ["sm", "md", "lg"]

  def render(assigns) do
    ~F"""
    <div id={@id} :hook="CardHook" class={"card", "max-w-#{@max_width}", "rounded-2xl": @rounded}>
      <div class="header">
        <#slot {@header} />
      </div>
      <div class="content">
        <#slot />
      </div>
      <div class="footer">
        <#slot {@footer} />
      </div>
    </div>
    """
  end
end
